blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://MyAgentive.ai
    about: Check our documentation for answers to common questions
  - name: Discussions
    url: https://github.com/AgentiveIS/MyAgentive/discussions
    about: Ask questions and discuss ideas with the community
